---
abstract: 'declare and retrieve named attributes about CODE'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0
  Module::Build::Compat: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Attribute-Storage
provides:
  Attribute::Storage:
    file: lib/Attribute/Storage.pm
    version: 0.07
requires:
  XSLoader: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
