---
name: Attribute-Storage
version: 0.04
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: |-
  declare and retrieve named attributes about CODE
  references
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.35
provides:
  Attribute::Storage:
    file: lib/Attribute/Storage.pm
    version: 0.04
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
