---
name: Attribute-Storage
version: 0.01
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: |-
  store and access named attributes about CODE
  references
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  Test::Refcount: 0
provides:
  Attribute::Storage:
    file: lib/Attribute/Storage.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
